# ----------------------------------------------------------------------------------------------------------------------
# Schemat opisu:
#  MaxPlanck_outdoor2.txt:  /nazwa pliku
#    time_interval: 1       /czas pomiędzy pomiarami
#    samples:
#      - x                  /kanał pierwszy na urządzeniu
#      - y                  /kanał drugi na urządzeniu (gdy nie jest nic podłączone to piszemy "skip"!)
#
# Pliki tutaj muszą być identyczne z plikami w folderze preprocessed. W przypadku gdy tu nie będzie pliku, a w preprocessed
# będzie, to plik zostanie pominięty. Gdy będzie sytuacja na odwrót to pojawi się błąd bo program nie znajdzie pliku
# ----------------------------------------------------------------------------------------------------------------------
samples_in_file:
  .example.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - skip
      - cellA
      - skip
      - cellB
      - skip
      - cellC
  .example_2.txt:
    time_interval: 10
    samples:
      - cellA
  .example_3.txt:
    time_interval: 10
    samples:
      - cellA

