# ----------------------------------------------------------------------------------------------------------------------
# Schemat opisu:
#  MaxPlanck_outdoor2.txt:  /nazwa pliku
#    time_interval: 1       /czas pomiędzy pomiarami
#    samples:
#      - x                  /kanał pierwszy na urządzeniu
#      - y                  /kanał drugi na urządzeniu (gdy nie jest nic podłączone to piszemy "skip"!)
#
# Pliki tutaj muszą być identyczne z plikami w folderze preprocessed. W przypadku gdy tu nie będzie pliku, a w preprocessed
# będzie, to plik zostanie pominięty. Gdy będzie sytuacja na odwrót to pojawi się błąd bo program nie znajdzie pliku
# ----------------------------------------------------------------------------------------------------------------------
samples_in_file:
  BPW37_outdoor.txt:
    time_interval: 1
    samples:
#      - x
  BPW37_outdoor2.txt:
    time_interval: 1
    samples:
#      - x
  BPW37_outdoor3.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor1.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor2.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor3.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor4.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor5.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor6.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor7.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor8.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor9.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor10.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor11.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor12.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor13.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor14.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor15.txt:
    time_interval: 1
    samples:
#      - x
  MaxPlanck_outdoor16.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor17.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor18.txt:
    time_interval: 1
    samples:
#      - x
#      - y
  MaxPlanck_outdoor19.txt:
    time_interval: 1
    samples:
      - 39B
      - 36B
      - 39D
      - 36D
      - 39E
      - 36E
      - skip
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor20_8channels_OBRIOBONE.txt:
    time_interval: 1
    samples:
      - 39B
      - 36B
      - 39D
      - 36D
      - 39E
      - 36E
      - skip
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor21_8channels_OBRIOBONE.txt:
    time_interval: 1
    samples:
      - 39B
      - 36B
      - 39D
      - 36D
      - 39E
      - 36E
      - skip
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor22_8channels_OBRIOBONE.txt:
    time_interval: 10
    samples:
      - 39B
      - 36B
      - 39D
      - 36D
      - 39E
      - 36E
      - skip
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor23_8channels_OBRIOBONE.txt:
    time_interval: 10
    samples:
      - 39B
      - 36B
      - 39D
      - 36D
      - 39E
      - 36E
      - skip
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor24_OBRIOBONE.txt:
    time_interval: 1
    samples:
      - 39B
      - 36B
      - 39D
      - 36D
      - 39E
      - 36E
      - skip
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor25.txt:
    time_interval: 1
    samples:
      - 36A
      - 39D
      - 36B
      - skip
      - 36C
      - skip
      - 36D
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor26.txt:
    time_interval: 1
    samples:
      - 36A
      - 39D
      - 36B
      - skip
      - 36C
      - skip
      - 36D
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor27.txt:
    time_interval: 1
    samples:
      - 36A
      - 39D
      - 36B
      - skip
      - 36C
      - skip
      - 36D
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor28.txt:
    time_interval: 1
    samples:
      - 36A
      - 39D
      - 36B
      - skip
      - 36C
      - skip
      - 36D
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor29.txt:
    time_interval: 1
    samples:
      - 36A
      - 39D
      - 36B
      - skip
      - 36C
      - skip
      - 36D
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor30.txt:
    time_interval: 10
    samples:
      - 36A
      - 39D
      - 36B
      - skip
      - 36C
      - skip
      - 36D
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  #MaxPlanck_outdoor31.txt:
   # time_interval: 10
    #samples:
     # - 36A
      #- 39D
      #- 36B
      #- skip
      #- 36C
      #- skip
      #- 36D
      #- skip
      #- skip
      #- skip
      #- skip
      #- skip
      #- Si

  #MaxPlanck_outdoor32.txt:
    #time_interval: 10
    #samples:
     # - 36A
      #- 39D
      #- 36B
      #- skip
      #- 36C
      #- skip
      #- 36D
      #- skip
      #- skip
      #- skip
      #- skip
      #- skip
      #- Si
      #- Si

  MaxPlanck_outdoor33_Si_only_13CH.txt:
    time_interval: 1
    samples:
      - 36A
      - 39D
      - 36B
      - skip
      - 36C
      - skip
      - 36D
      - skip
      - skip
      - skip
      - skip
      - skip
      - Si

  MaxPlanck_outdoor34_NREL_D15_D12.txt:
    time_interval: 1
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36B
      - skip
      - 36C
      - skip
      - 36D


  MaxPlanck_outdoor35NREL_D15_D12.txt:
    time_interval: 30
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36B
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor36NREL_D15_D12.txt:
    time_interval: 30
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36B
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor37NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36B
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor38NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36B
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor39NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36B
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor40NREL_D15_D12.txt:
    time_interval: 10
    samples :
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36B
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor41NREL_D15_D12.txt:
    time_interval: 10
    samples :
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor42NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor43NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

 # MaxPlanck_outdoor44NREL_D15_D12.txt:
  #  time_interval: 10
   # samples:
    #  - skip
     # - Si
      #- skip
      #- skip
      #- skip
      #- skip
      #- 36C
      #- skip
      #- 36D

  MaxPlanck_outdoor45NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor46NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor47NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor48NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor49NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor50NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor51NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor52NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor53NREL_D15_D12.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor54NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor55NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor56NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor57NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor58NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor59NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor60NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor61NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor62NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor63NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor64NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor65NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor66NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor67NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor68NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor69NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor70NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor71NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor72NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor73NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor74NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor75NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor76NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor77NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor78NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor79NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor80NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D

  MaxPlanck_outdoor81NREL_D15.txt:
    time_interval: 10
    samples:
      - skip
      - Si
      - skip
      - skip
      - skip
      - skip
      - 36C
      - skip
      - 36D